### ISSUE TITLE
Hibernate naming strategy

### ISSUE THREAD

**Issue by dacrome** [osiam/resource-server#11]
The default naming strategy of hibernate is the [EJB3NamingStrategy](https://docs.jboss.org/hibernate/entitymanager/3.6/reference/en/html/configuration.html#d0e708). The strategy maps camel case attributes like [`userName`](https://github.com/osiam/resource-server/blob/master/src/main/java/org/osiam/storage/entities/UserEntity.java#L47) to the column name `username`. When switching to Spring Boot, the default naming strategy is set by Boot to [ImprovedNamingStrategy](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-configure-jpa-properties). This leads to problems with the column names of camel case entity attributes which are not annotated with `@Column` and a set `name` parameter (e.g. @Column(name = "username") ). I think we should use the [ImprovedNamingStrategy](https://docs.jboss.org/hibernate/orm/4.3/javadocs/org/hibernate/cfg/ImprovedNamingStrategy.html) before migrate to Spring Boot and add flyway migrations for postgres and mysql to use underscores for mixed case names.

**Comment by tkrille** [comment]
Sounds good and makes the DBAs happy. Currently, the field names are somewhat ... messed up.
