### ISSUE TITLE
Build Debian packages in this repo

### ISSUE THREAD

**Issue by tkrille** [osiam/resource-server#16]
This repo should contain stuff so that a Debian package can be build. It's still open whether we should use vanilla Debian packaging scripts and stuff, or maybe use the excellent [pkg-maven-plugin](https://github.com/tarent/pkg-maven-plugin). I would recommend the [pkg-maven-plugin](https://github.com/tarent/pkg-maven-plugin).

**Comment by dacrome** [comment]
If we migrate to gradle we can not use the pkg-maven-plugin, so maybe then using this [gradle-debian-plugin](https://github.com/gesellix/gradle-debian-plugin)?

**Comment by wallner** [comment]
Yes, that one looks promising. Although, let me ask the heretic question here: Do we really still want to provide os packages? I would like to just provide official docker images, can't we get away with that?

**Comment by tkrille** [comment]
@dacrome Yes, we will look for a Gradle plugin then. Is the one you found already the best? Because we have to write control files on our own and also have to supply the `changelog` file that contains the version and, of course, the complete changelog for each version. This seems hard to maintain unless we find a way to completely automate it.

@wallner I think, if it's not much work (opposed to the current Debian packages) to create a build process, and update and maintain the packages, it's a really cool feature. Of course, we should provide RPM packages, too. Not everybody uses or wants to use Docker yet, so we cannot say: "Here are a bunch of jar files, look in the documentation how to deploy them for production, or just use the Docker images."

**Comment by dacrome** [comment]
Moved to https://github.com/osiam/osiam/issues/64
