### ISSUE TITLE
Switch from xml to java configuration

### ISSUE THREAD

**Issue by dacrome** [osiam/resource-server#20]
The xml configuration should be removed and migrate to java configuration. The Spring Framework provides java configuration since version 3.1 and this can be done as a first step to [Spring Boot](http://projects.spring.io/spring-boot/). We already made good experience with the configuration migration in the [self-administration](https://github.com/osiam/addon-self-administration/pull/118). We should check if this step can be used to migrate [Spring OAuth2 version 1.0.5.RELEASE](https://github.com/osiam/resource-server/blob/master/pom.xml#L102) to the latest version 2.0.7.RELEASE to take advantage of the new configuration annotations. Maybe also a bump of the [Spring Security version](https://github.com/osiam/resource-server/blob/master/pom.xml#L80) to the latest 4.0.1.RELEASE is possible.

**Comment by tkrille** [comment]
Looking forward to see the PR for this.

**Comment by wallner** [comment]
I will do this one.

**Comment by tkrille** [comment]
@dacrome This also includes migrating to `spring-security-oauth` 2.0?

**Comment by dacrome** [comment]
Yes, this includes the migrating to `spring-security-oauth` 2.0 ... I already began with the [switch to java config](https://github.com/dacrome/resource-server/tree/switch-to-java-config). I forgot to assign this issue to me. This is also true for some other spring boot issues. I will fix this later. Sorry, this isn't transparent as it should be.
