### ISSUE TITLE
Spring Boot fat war

### ISSUE THREAD

**Issue by dacrome** [osiam/resource-server#21]
As a pre step to a fully standalone application in form of a Spring Boot fat jar, we should migrate the resource-server [after the configuration migration](https://github.com/osiam/resource-server/issues/20) to a fat war which is deployable like before. This was already done in the [self-administration](https://github.com/osiam/addon-self-administration/pull/125) and we made good experience with the split into small migration steps. Next stop: fat jar!

**Comment by tkrille** [comment]
Where's the PR? :)
