### ISSUE TITLE
Run the resource-server as a standalone application

### ISSUE THREAD

**Issue by dacrome** [osiam/resource-server#22]
Like [already discussed](https://github.com/osiam/osiam/issues/5) in the OSIAM umbrella repo, the time is right to support standalone application with Spring Boot fat jars. I already created pre steps in form of issues in this repo, to reach the goal of a standalone application without the currently ugly deployment!

**Comment by tkrille** [comment]
Part of: osiam/osiam#5

**Comment by tkrille** [comment]
Are we doing this like we did it with the addon-self-administration, i.e.
1. Move XML to Java config
2. Introduce Spring Boot
3. Switch to Fat-JAR deployment

**Comment by tkrille** [comment]
I formalized this in #43 and made this issue somewhat obsolete. Sorry 'bout that.
