### ISSUE TITLE
Wrong schema for SCIMSearchResult

### ISSUE THREAD

**Issue by tkrille** [osiam/resource-server#33]
Moved from [Jira](https://jira.osiam.org/browse/BT-20):

> the schema in the ScimSearchResult ist at the moment e.g. 
> 
> [urn:scim:schemas:core:2.0:User]
> 
> But according to
> http://tools.ietf.org/html/draft-ietf-scim-api-02#section-3.2.2
> it should be like 
> ["urn:scim:schemas:core:2.0:ListResponse"]

**Comment by tkrille** [comment]
Should be easily fixable. See `org.osiam.resources.provisioning.SCIMUserProvisioning#search`.

**Comment by fwilhe** [comment]
Does anyone want to review my fix? @tkrille @wallner @dacrome

**Comment by thomasdarimont** [comment]
I think the item `Wrong schema for SCIMSearchResult` in issue [25](https://github.com/osiam/osiam/issues/25) can be marked as completed.

**Comment by dacrome** [comment]
> I think the item Wrong schema for SCIMSearchResult in issue 25 can be marked as completed.

Done. Thanks!

**Comment by thomasdarimont** [comment]
:thumbsup:
