### ISSUE TITLE
Add /Schemas endpoint

### ISSUE THREAD

**Issue by thomasdarimont** [osiam/resource-server#47]
The section about Service Provider Configuration Endpoints of the [SCIM Specification](https://tools.ietf.org/html/draft-ietf-scim-api-19#section-4) describes a `/Schemas` endpoint that enables clients to discover the list of supported Schemas.

**Comment by dacrome** [comment]
Good catch! We need to focus on staying consistent with the SCIM spec. This is no big deal and will be done soon.

**Comment by dacrome** [comment]
Moved to https://github.com/osiam/osiam/issues/73
