### ISSUE TITLE
Create meaningful log message if auth-server can't be reached.

### ISSUE THREAD

**Issue by wallner** [osiam/resource-server#52]
As @mirabilos pointed out in [auth-server#55](https://github.com/osiam/auth-server/issues/55) the resource server doesn't generate a meaningful log message if it refuses to validate an access token because of an unreachable auth server.

**Comment by tkrille** [comment]
Yes, it should log such a scenario. But just a simple log message, without stacktrace. Otherwise the log will be bloated after a few minutes on a busy resource server.
