### ISSUE TITLE
Metrics broken

### ISSUE THREAD

**Issue by tkrille** [osiam/resource-server#58]
Since #20/#50 the `/Metrics` endpoint does not report any data. This obviously happened because no one configured it within the new Java config. See https://github.com/ryantenney/metrics-spring#basic-usage for details.

**Comment by dacrome** [comment]
/Metrics returns an empty body? I'm sorry, I only created a [MetricRegistry Bean](https://github.com/osiam/resource-server/blob/master/src/main/java/org/osiam/ResourceServer.java#L154) but didn't do anything else. I think we should leave it like this and use the [Spring Boot Actuator](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready) when #53 is merged. There is also a discussion about the monitoring and metrics of the backend components [in the umbrella repo](https://github.com/osiam/osiam/issues/8).

**Comment by tkrille** [comment]
Sounds good to me.

**Comment by dacrome** [comment]
I thought about it again. The /Metrics endpoint should report data again, because the goal was to create a Spring Boot fat war which is runnable like before.

**Comment by tkrille** [comment]
> the goal was to create a Spring Boot fat war which is runnable like before

You mean without actuator? Then we have to fix this, yes.

**Comment by tkrille** [comment]
@dacrome 

> > the goal was to create a Spring Boot fat war which is runnable like before
> 
> You mean without actuator? Then we have to fix this, yes.

**Comment by dacrome** [comment]
Yes without the actuator. I add the [`@EnableMetrics`](https://github.com/osiam/resource-server/pull/53/files#diff-ab1300a22470d8e3064a767693648929R39) to the Spring Boot PR #53, but this isn't enough I need to configure it.

**Comment by dacrome** [comment]
Now it behaves like before.

**Comment by tkrille** [comment]
Cool, so this will be solved by #53 too?

**Comment by dacrome** [comment]
Yes
