### ISSUE TITLE
Remove unnecessary AOP profiling feature

### ISSUE THREAD

**Issue by wallner** [osiam/resource-server#59]
We have the home grown profiling solution that is implemented as an aspect in `MeasureDurationTimeOfMethods`. It never was the most elegant solution to begin with and since we have introduced the most excellent [metrics framework](https://github.com/dropwizard/metrics) it is now time for this  implementation to go. I suggest that we remove it.

**Comment by tkrille** [comment]
Agreed, I will do this as soon as #53 is merged.

**Comment by wallner** [comment]
Just did that quickly

**Comment by tkrille** [comment]
Where's the PR? :)

**Comment by wallner** [comment]
Here: #63
