### ISSUE TITLE
Problem with "not"-Filter

### ISSUE THREAD

**Issue by tkrille** [osiam/resource-server#7]
_Moved from https://github.com/osiam/server/issues/247_

@sschum:

> It seams that is a bug in the filter mechanism. Even if I use the "not" filter, the result is not that what I would expect! 
> 
> For example: 
> 1) I want to search all users that are NOT included in a given group. Than I want to use the following filter: `not(groups eq "<groupId>")`
> 2) I want to search all groups in which is the user NOT a member. Than I want to use the following filter: `not(members eq "<userId>")`
> 
> In the following I have create a little JUnit-Test-File. In there the use-cases demonstrated.
> EDIT: here is the gist-link: https://gist.github.com/sschum/ad6a09a2e70ae95ad1ce

@dacrome:

> I will check this bug. Thanks for sharing!
> 
> ...and please post your example code next time in a [gist](https://gist.github.com/) and copy the link here :) or you open a PR to the [integration-tests](https://github.com/osiam/connector4java-integration-tests) of OSIAM for easy verify :) thank you!

**Comment by tkrille** [comment]
Here's an example by @sputnik27 that works: https://gist.github.com/fwilhe/5f29604ab7770e824969

The question is now: should we change the behaviour of the `eq` operator or should we create a new, custom operator called `in`?

**Comment by dacrome** [comment]
I like the custom operator `in`.

**Comment by wallner** [comment]
can you give an example query for both options, so we are all clear what we are talking about?

**Comment by tkrille** [comment]
@wallner Something like:

```
groups eq "Department 1"
groups in "Department 1"
```

Or what do you mean?

**Comment by tkrille** [comment]
Ok: `groups in "Department 1"` reads odd, because of the obvious wrong order of operands. Maybe `groups hasItem "Department 1"` is more appropriate.

**Comment by tkrille** [comment]
The opposite would then be:

```
not (groups hasItem "Department 1")
```

But this reads kind of odd, too.

**Comment by tkrille** [comment]
Ok, this has been verified as a bug by the people of SCIM: http://www.ietf.org/mail-archive/web/scim/current/msg02497.html and the answer: http://www.ietf.org/mail-archive/web/scim/current/msg02498.html. This means, that we have to change every implementation of each operator. As we can only solve this issue by adding sub-selects, this could also lead to a slight performance degradation. @sschum @timopick @tpick What do you think?

**Comment by dacrome** [comment]
Moved to https://github.com/osiam/osiam/issues/61
